config/routes.rb
Rails.application.routes.draw do

  get 'users/show'

  get 'likes/index'

  resources :topics do
    resources :bookmarks, except: [:index]
  end

  resources :bookmarks do
    resources :likes, only: [:index, :create, :destroy]
  end

  devise_for :users
  resources :users, only: [:show]

  get 'welcome/about'

  root 'welcome#index'

  post :incoming, to: 'incoming#create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :topic
  belongs_to :user
  has_many :likes, dependent: :destroy

  validates :url, presence: true
  # validates :user, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :bookmark
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :user
  has_many :bookmarks, dependent: :destroy

  validates :title, length: { minimum: 3 }, presence: true

  include FriendlyId

  friendly_id :title, use: :slugged
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase if email.present? }

  validates :email, length: { minimum: 4, maximum: 100 }, presence: true

  has_many :topics, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :likes, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable

  def liked(bookmark)
    likes.where(bookmark_id: bookmark.id).first
  end

  def user_liked_bookmarks
    likes.includes(bookmark: :topic).map(&:bookmark)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  before_action :authenticate_user!

  protect_from_forgery with: :exception
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :authenticate_user!, except: [:index, :about]
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # before_action :authorize_user, except: [:index, :about, :show]

  def new
    @topic = Topic.friendly.find(params[:topic_id])
    @bookmark = Bookmark.new
  end

  def create
    # @user = current_user
    @topic = Topic.friendly.find(params[:topic_id])
    @bookmark = @topic.bookmarks.build(bookmark_params)
    @bookmark.user = current_user

    if @bookmark.save
      flash[:notice] = "Bookmark saved successfully"
      # redirect_to [@topic, @bookmark]
    else
      flash.now[:alert] = "You need to be logged in to save bookmarks."
      # render :new
    end
    redirect_to @topic
  end

  def update
    @bookmark = Bookmark.find(params[:id])
    @bookmark.assign_attributes(bookmark_params)

    if @bookmark.save
      flash[:notice] = "Bookmark was updated successfully."
    else
      flash.now[:alert] = "There was an error saving the bookmark."
    end
    redirect_to @bookmark.topic
  end

  def edit
    @bookmark = Bookmark.find(params[:id])
  end

  def show
    @bookmark = Bookmark.find(params[:id])
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    authorize @bookmark

    if @bookmark.destroy
      flash[:notice] = "\"#{@bookmark.url}\" was deleted successfully."
    else
      flash.now[:alert] = "There was an error deleting the bookmark."
    end
    redirect_to @bookmark.topic
  end


  private
  def bookmark_params
    params.require(:bookmark).permit(:url)
  end

  def user_not_authorized
    flash[:alert] = "You must be the owner or admin to do that."
    redirect_to (request.referrer || root_path)
  end

end

app/controllers/incoming_controller.rb
class IncomingController < ApplicationController

  # http://stackoverflow.com/questions/1177863/how-do-i-ignore-the-authenticity-token-for-specific-actions-in-rails
  skip_before_action :verify_authenticity_token, only: [:create]
  before_action :authenticate_user!, except: [:create]

  def create

     puts "INCOMING PARAMS HERE: #{params}"
     @user = User.find_by_email(params[:sender])
     if @user.nil?
       @user = User.create(email: params[:sender], password: "password1")
       @user.save
     end

     @topic = Topic.find_or_create_by(title: params[:subject], user_id: @user.id)
     @bookmark = @topic.bookmarks.find_or_create_by(url: params["body-plain"])

     head 200
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :about]

  def index
    @likes = Like.all
  end

  def create
    @bookmark = Bookmark.find(params[:bookmark_id])
    like = current_user.likes.build(bookmark: @bookmark)

    authorize like
    if like.save
      flash[:notice] = "'Like' was saved."
    else
      flash.now[:alert] = "There was an error saving your 'Like'."
    end
    redirect_to @bookmark.topic
  end

  def destroy
    @bookmark = Bookmark.find(params[:bookmark_id])
    like = current_user.likes.find(params[:id])

    authorize like
    if like.destroy
      flash[:notice] = "'Like' was removed."
    else
      flash.now[:alert] = "There was an error removing your 'Like'."
    end
    redirect_to @bookmark.topic
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :about]

  def index
    @topics = Topic.all
  end

  def show
    @topic = Topic.friendly.find(params[:id])
    @bookmarks = @topic.bookmarks
  end

  def new
    @topic = Topic.new
  end

  # def edit
  #   @topic = topic.find(params[:id])
  # end

  def create
    @user = current_user
    @topic = @user.topics.build(topic_params)

    if @topic.save
      flash[:notice] = "Topic was saved successfully."
      redirect_to @topic
    else
      # flash.now[:alert] = "Error creating topic. Please try again."
      flash.now[:alert] = "You need to sign in or sign up before continuing."
      render :new
    end
  end

  def destroy
    @topic = Topic.friendly.find(params[:id])

    if @topic.destroy
      flash[:notice] = "\"#{@topic.title}\" was deleted successfully."
      redirect_to topics_path
    else
      flash.now[:alert] = "There was an error deleting the post."
      render :show
    end
  end

  private

  def topic_params
    params.require(:topic).permit(:title)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    @user_bookmarks = @user.bookmarks.group_by{ |s| s.topic }
    @liked_bookmarks = @user.user_liked_bookmarks.group_by(&:topic)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!, except: [:index, :about]

  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
require 'embedly'
require 'json'

module ApplicationHelper
  def disp_embedly(url)
    embedly_api = Embedly::API.new :key => ENV['EMBEDLY_API_KEY'], :user_agent => 'Mozilla/5.0 (compatible; mytestapp/1.0; my@email.com)'
    obj = embedly_api.oembed :url => url
    obj[0].marshal_dump
  end
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bookmarks/_bookmark.html.haml
= content_tag :tr, class: "media", id: "bookmark-#{bookmark.url}" do
  .thumbnail
    %img{:alt => ""}
      - embedly = disp_embedly(bookmark.url)
      = link_to embedly[:url], :target => '_blank' do
        = image_tag embedly[:thumbnail_url]
        - if current_user
          %td= link_to "Edit", edit_topic_bookmark_path(bookmark.topic, bookmark)
          %td= link_to "Delete", [bookmark.topic, bookmark], method: :delete
          %td= render partial: 'likes/like', locals: { bookmark: bookmark }

app/views/bookmarks/create.html.erb
<h1>Bookmarks#create</h1>
<p>Find me in app/views/bookmarks/create.html.erb</p>

app/views/bookmarks/destroy.html.erb
<h1>Bookmarks#destroy</h1>
<p>Find me in app/views/bookmarks/destroy.html.erb</p>

app/views/bookmarks/edit.html.haml
%h1 Edit bookmark

.row
  .col-md-8
    = form_for [@bookmark.topic, @bookmark] do |f|
      .form-group
        = f.label :url
        = f.txt_field :url, class: 'form-control', placeholder: "Enter bookmark url."
      .form-group
        = f.submit "Save", class: 'btn btn-success'

app/views/bookmarks/new.html.haml
%h1 New Bookmarks
.row
  .col-md-8
    = form_for [@topic, @bookmark] do |f|
      .form-group
        = f.label :url
        = f.text_field :url, class: 'form-control', placeholder: "Enter bookmark url."
      .form-group
        = f.submit "Save", class: 'btn btn-success'

app/views/bookmarks/show.html.erb
<h1> <%= @bookmark.url %> </h1>
<!-- #%h1= @bookmark.url -->
<!-- <div class="row">
  <div class="col-md-8">
    <p><%= @bookmark.url %></p>
  </div>
  <div class="col-md-4">
    <%= link_to "Edit", edit_topic_bookmark_path(@bookmark), class: 'btn btn-success' %>
  </div>
</div> -->

app/views/bookmarks/show.html.haml
<!-- <h1> <%#= @bookmark.url %> </h1> -->
%h1= @bookmark.url
<!-- <div class="row">
  <div class="col-md-8">
    <p><%= @bookmark.url %></p>
  </div>
  <div class="col-md-4">
    <%= link_to "Edit", edit_topic_bookmark_path(@bookmark), class: 'btn btn-success' %>
  </div>
</div> -->

app/views/bookmarks/update.html.erb
<h1>Bookmarks#update</h1>
<p>Find me in app/views/bookmarks/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Markme</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-collapse collapse" id="navbar-main">
          <ul class="nav navbar-nav">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Topics", topics_path %></li>
            <li><%= link_to "My Info", users_show_path%></li>
            <li><%= link_to "About", welcome_about_path %></li>
          </ul>
          <div class="pull-right user-info">
            <% if user_signed_in? %>
              Signed in as: <strong><%= current_user.email %></strong>
              <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
            <% else %>
              <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link' %> -
              <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link' %>
            <% end %>
          </div>
      </div>
      <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash.now[:alert] %>
        <div class="alert alert-danger">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash.now[:alert] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-warning">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>
    </div>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/likes/_like.html.haml
- if policy(Like.new).create?
  %div
    - if like = current_user.liked(bookmark)
      = link_to [bookmark, like], class: "btn btn-danger", method: :delete do
        %i.glyphicon.glyphicon-star-empty>
        \  Unlike
    - else
      = link_to [bookmark, Like.new], class: 'btn btn-primary', method: :post do
        %i.glyphicon.glyphicon-star>
        \  Like

app/views/likes/index.html.erb
<h1>Likes#index</h1>
<p>Find me in app/views/likes/index.html.erb</p>

app/views/topics/edit.html.erb
<h1>Topics#edit</h1>
<p>Find me in app/views/topics/edit.html.erb</p>

app/views/topics/index.html.haml
%h1 Topics
.row
  .col-md-8
    - @topics.each do |topic|
      .media
        .media-body
          %h4.media-heading
            = link_to topic.title, topic
  .col-md-4
    = link_to "New Topic", new_topic_path, class: 'btn btn-success'

app/views/topics/new.html.haml
%h1 New Topic
.row
  .col-md-4
    %p Guidelines for Topics
    %ul
      %li Make sure it rhymes.
      %li Don't use the letter "A".
      %li The incessant use of hashtags will get you banned.
  .col-md-8
    = form_for @topic do |f|
      .form-group
        = f.label :title
        = f.text_field :title, class: 'form-control', placeholder: "Enter topic title"
      .form-group
        = f.submit "Save", class: 'btn btn-success'

app/views/topics/show.html.haml
%h1 Topics
.row
  .col-md-8
    %p.lead= @topic.title
    = link_to "Delete Topic", @topic, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this topic?'}
%h3 My Bookmarks
.row
  .col-md-8
    .media
      .media-body
        %table.table.table-hover
          %tbody
            %tr.js-items= render @bookmarks
= link_to "New Bookmark", new_topic_bookmark_path(@topic), class: 'btn btn-success'

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.haml
%h3 My Bookmarks
.row
  .col-md-8
    - @user_bookmarks.each do |topic, bookmarks|
      %h4= link_to topic.title, topic_path(topic)
      .media
        .media-body
          %table.table.table-hover
            %tbody
              %tr.js-items
                - bookmarks.each do |bookmark|
                  = render partial: 'bookmarks/bookmark', locals: { topic: bookmark.topic, bookmark: bookmark}
  .col-md-4
    = link_to "New Topic", new_topic_path, class: 'btn btn-success'
%h3 My Liked Bookmarks
.row
  .col-md-8
    - @liked_bookmarks.each do |topic, bookmarks|
      %h4= link_to topic.title, topic_path(topic)
      .media
        .media-body
          %table.table.table-hover
            %tbody
              %tr.js-items
                - bookmarks.each do |bookmark|
                  = render partial: 'bookmarks/bookmark', locals: { topic: bookmark.topic, bookmark: bookmark}

app/views/welcome/about.html.haml
%h1 About MarkMe
%p Created by: Me

app/views/welcome/index.html.haml
%h1 Welcome to MarkMe